### ISSUE TITLE
The field PDFStreamEngine.operators is not visible

### ISSUE THREAD

**Issue by Meloweh** [acid1103/PDFInverter#4]
PDFColorInverter >> "OperatorProcessor processor = operators.get(name);" >> "The field PDFStreamEngine.operators is not visible"

**Comment by acid1103** [comment]
So I'm using a modified version of pdfbox specifically to make that field and one other visible. Using this modified version is relatively simple. When cloning this repo, issue the following commands:
```
git clone --recurse-submodules https://github.com/acid1103/PDFInverter.git
cd pdfbox
mvn install
cd ..
gradle buildAndMaybeRelease
```
Then the project should be built at `build/libs/PDFInverter.jar`.
