### ISSUE TITLE
PDF Content Stream Truncated For Some Files

### ISSUE THREAD

**Issue by FraH90** [acid1103/PDFInverter#5]
Hi, I'm using this fantastic tool to automatically invert PDF colors, so I can use the on the ipad importing in Notability and writing on them, like some kinda of dark mode.

I was trying to convert a [pdf](https://github.com/acid1103/PDFInverter/files/6260470/January.pdf) that appears to contain JPG image.

however, after launching the command I get several of the errors I've reported in the title:

`Loading C:\Users\***\Desktop\PDFInverter\January.pdf...
gen 01, 2021 5:58:23 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
GRAVE: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
gen 01, 2021 5:58:23 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
GRAVE: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
gen 01, 2021 5:58:23 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
GRAVE: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
gen 01, 2021 5:58:23 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
GRAVE: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
gen 01, 2021 5:58:23 PM org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
GRAVE: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
[0.0, 0.0, 0.0] -> [1.0, 1.0, 1.0]
[0.0, 0.0, 0.0] -> [1.0, 1.0, 1.0]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 313
        at java.lang.String.substring(Unknown Source)
        at org.apache.pdfbox.contentstream.PDFColorInverter.invert(PDFColorInverter.java:321)
        at org.abitoff.pdfinverter.Main.main(Main.java:90)
`

It seems that is missing some jpg related library, I've looked for the error on internet and it seems that's the case.
Some guys said something that there's need to link the library jai-imageio-jpeg2000-1.4.0.jar in the project, and it speaked about gradle, so I guess that it's necessary to implement this feature directly from code, linking the library with the PDFInverter project).

I would do it myself, but I have zero java experience, I just program some batch files and python sometimes. 
Hope you would consider to fix this and implement inversion also for those images!
(I've tried disabling the inversion of the images with the boolean value, but you still get the error)

**Comment by acid1103** [comment]
Hi, apologies for the late reply. It looks like you've stumbled upon some weird issue deeper within either my application or the PDFBox library I'm using to do most of the heavy lifting.
It will take me some time to dig around to find the root issue, but it has something to do with PDFBox not giving me all the information about this PDF. (Specifically, PDPage.getContents() seems to be returning a truncated InputStream on this PDF. That's what's causing the StringIndexOutOfBoundsException [here](https://github.com/acid1103/PDFInverter/blob/1827f783aa3016aea4c94b82fe020edbef6017f2/src/main/java/org/apache/pdfbox/contentstream/PDFColorInverter.java#L321).)
The JAI Image I/O Tools warnings seem to be unrelated, but I will push a fix for that warning at the same time I fix the underlying cause of this crash. In either case, thanks for reporting the issue, and thanks for providing a link to your PDF! It really helps with the debugging process. I'll push a fix as soon as I can.

**Comment by FraH90** [comment]
> Hi, apologies for the late reply. It looks like you've stumbled upon some weird issue deeper within either my application or the PDFBox library I'm using to do most of the heavy lifting.
> It will take me some time to dig around to find the root issue, but it has something to do with PDFBox not giving me all the information about this PDF. (Specifically, PDPage.getContents() seems to be returning a truncated InputStream on this PDF. That's what's causing the StringIndexOutOfBoundsException [here](https://github.com/acid1103/PDFInverter/blob/1827f783aa3016aea4c94b82fe020edbef6017f2/src/main/java/org/apache/pdfbox/contentstream/PDFColorInverter.java#L321).)
> The JAI Image I/O Tools warnings seem to be unrelated, but I will push a fix for that warning at the same time I fix the underlying cause of this crash. In either case, thanks for reporting the issue, and thanks for providing a link to your PDF! It really helps with the debugging process. I'll push a fix as soon as I can.

Hi, I've found what could be the problem with this error we had.

it seems that you need to add some dependencies in the gradle config file, specifically:

```
    implementation 'com.github.jai-imageio:jai-imageio-core:1.4.0'
    implementation 'com.github.jai-imageio:jai-imageio-jpeg2000:1.3.0'
    implementation 'org.apache.pdfbox:jbig2-imageio:3.0.3'      // to avoid the same error with JBIG2 images
```

I've tried doing it by myself, forking your work but I've not been able to compile it (I'm not very practical with java environments, I've downloaded the JDK, installed gradle, even tried with IntelliJIdea but I havent been successfull. 

Could you please provide some instruction for compilation of this project (like how you need to setup the build environment) or implement this change yourself in your code and recompile it? So i can use this library with the pdf I provided you earlier?

Thanks very much in advance for your response.

**Comment by FraH90** [comment]
PS: you were right however, the error is given by the library you're using, pdfbox, which needs those dependencies in order to work correctly with some image formats.

**Comment by acid1103** [comment]
Hi, Frah90. Sorry for being slow to fix this issue. Various circumstances have resulted in this project being placed on hold for the time being. I'll try to look further into this issue tonight or sometime next week, but if I remember correctly from my earlier testing, this seems to be an underlying issue with the pdfbox library I'm using to process the PDF files. If that turns out to be the case, I will end up transferring this issue to them.

**Comment by acid1103** [comment]
I've opened an issue with the pdfbox developers. You can find it [here](https://issues.apache.org/jira/browse/PDFBOX-5152).
